### ISSUE TITLE
プルリクエストのやり方の説明をおねがいします。

### ISSUE THREAD

**Issue by hsk** [yutopp/rill#26]
プルリクエストくれと書かれているのですが協力の仕方がよくわかりません。
面倒くさいから良いやとなるのはもったいないので、どのような手順でどのようにすればリクエストを受け付けてくれるのかを説明してあると、協力が得やすいのではないかと思います。
協力したいと思った場合にしやすい環境の構築をおねがいします。

**Comment by yutopp** [comment]
ありがとうございます。なるべく作れるよう努力します。。。
